The-Heroes-Journey-EQEMU/quests_public

thedeep/A_burrower_parasite.lua, thedeep/The_Burrower_Beast.lua
- Tested functions on my server with no issues.
=> Burrower Cleanup

potranquility/Elder_Poxbourne.lua
Fixes poxbourne flagging bugs
1) `poxbourner`
2) checking for his own flag instead of hedge flag
=> Fix poxbourne flagging

poinnovation/player.lua
=> Fixes broken poinnovation door

potranquility/Elder_Fuirstel.lua
Elder should be checking if his flag is _not_ set (so that he can set it)
=> Fixes invalid flag check on Elder Fuirstel

pojustice/201078.lua, pojustice/201434.lua, pojustice/201435.lua, pojustice/201436.lua, pojustice/201437.lua, pojustice/201438.lua
Fixes bugs in execution and flame trials
=> More trial fixes in Justice

hohonora/Minok_Targsk.pl, podisease/player.lua, postorms/player.lua, povalor/Grenic_Drere.lua
Fixes some additional alt access issues flagged by Mehus
=> Fix a few alt access issues

potranquility/player.lua
Fixing flag requirements for solrotower
=> Fixes solrotower flag requirements

potranquility/Miak_the_Searedsoul.lua
=> fix miak typo

ponightmare/Thelin_Poxbourne.pl
Cleaning up Thelin perl script
=> More thelin cleanup

ponightmare/#Thelin_Poxbourne.lua, ponightmare/#a_construct_of_nightmares.pl, ponightmare/Hedge_Trigger.pl, ponightmare/Thelin_Poxbourne.pl
=> More maze fixes

ponightmare/__Thelin_Poxbourne.lua
=> lua comments

ponightmare/__Thelin_Poxbourne.lua
=> This is gonna be the one

ponightmare/__Thelin_Poxbourne.lua
This one is though.
Thelin is done.
=> Spoiler: It was not the one

poearthb/#rathe_controller.lua
Move rathe council controller away from counter based logic to NPC is spawned logic.
=> Rathe council zonestate fix

potactics/#Rallos_Zek.lua, potactics/#Rallos_Zek_the_Warlord.lua, potactics/#Tallon_Zek.lua, potactics/#Vallon_Zek_.lua
commented out failure timers on RZTWL events (TZ/VZ/RZTWL)
=> remove failure timers on RZTWL

potimeb/player.lua
So basically if anyone said anything in p3, it wiped out the variable.  Shun me.... shun me good
=> Fix phase 3 resetting

firiona/Tracker_Azeal.pl
added _ between unique and spawn
=> Tracker Azeal Change

firiona/Tracker_Azeal.pl, potactics/##Vallon_Zek_.lua
adjusted to prevent nil values
=> Vallon zek

firiona/Tracker_Azeal.pl, postorms/Relv_the_Mysterious.lua
initial creation of Relv the Mysterious
=> Eld relv the mysterious

firiona/Tracker_Azeal.pl, postorms/Relv_the_Mysterious.lua, steamfont/Cargo_Clockwork.lua
converted to lua  to fix quest errors
=> Cargo clockwork
